# Generated by Django 4.1.5 on 2023-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_tag_type'),
        ('users', '0012_profile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='user_tags', to='blog.tag'),
        ),
    ]
