# Generated by Django 4.1.5 on 2023-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_profile_to_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="to_review",
        ),
    ]
