# Generated by Django 4.1.5 on 2023-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_remove_profile_to_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first",
            field=models.IntegerField(default=0),
        ),
    ]
