# Generated by Django 4.1.5 on 2023-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_profile_first"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blob_image",
            field=models.TextField(blank=True, db_column="data"),
        ),
    ]
