# Generated by Django 4.1.5 on 2023-01-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='defult.pdf', upload_to='documents/'),
        ),
    ]
