# Generated by Django 4.1.5 on 2023-01-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='third',
            field=models.TextField(default='dfsdfsd'),
            preserve_default=False,
        ),
    ]
