# Generated by Django 4.1.5 on 2023-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_thread_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='reciever_user',
            new_name='receiver_user',
        ),
    ]
