# Generated by Django 4.1.5 on 2023-01-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_reciever_user_messagemodel_receiver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
