# Generated by Django 4.1.5 on 2023-01-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_content_post_abstract_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Abstract',
            new_name='abstract',
        ),
    ]
