# Generated by Django 4.1.5 on 2023-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('User', 'USER'), ('Post', 'POST'), ('Both', 'BOTH')], default='Post', max_length=4),
        ),
    ]
