# Generated by Django 4.1.5 on 2023-02-09 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_alter_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(related_name='tag_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
