# Generated by Django 4.1.5 on 2023-02-13 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_tag_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
