# Generated by Django 4.1.5 on 2023-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0025_remove_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
