# Generated by Django 4.1.5 on 2023-02-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0026_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="primary_tag",
            field=models.ForeignKey(
                default=23, on_delete=django.db.models.deletion.CASCADE, to="blog.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
