# Generated by Django 4.1.5 on 2023-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0027_post_primary_tag_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="seconday_tags",
            field=models.ManyToManyField(related_name="secondary_tag", to="blog.tag"),
        ),
    ]
