# Generated by Django 4.1.5 on 2023-02-14 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0028_post_seconday_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="seconday_tags",
            new_name="secondary_tags",
        ),
    ]
