# Generated by Django 4.1.5 on 2023-02-16 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0032_remove_messagemodel_primary_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="type",
        ),
    ]
