# Generated by Django 4.1.5 on 2023-02-17 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0034_alter_post_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publication_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 17, 12, 37, 40, 218855)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
