# Generated by Django 4.1.5 on 2023-02-17 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0035_post_publication_date_alter_post_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 17, 12, 39, 15, 502460)
            ),
        ),
    ]
