# Generated by Django 4.1.5 on 2023-02-17 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0040_alter_post_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="publication_date",
        ),
    ]
