# Generated by Django 4.1.5 on 2023-02-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0042_post_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="identifier",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="publication_date",
            field=models.DateField(),
        ),
    ]
