# Generated by Django 4.1.5 on 2023-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0043_post_identifier_alter_post_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
