# Generated by Django 4.1.5 on 2023-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0045_alter_post_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="version",
            field=models.FloatField(),
        ),
    ]
