# Generated by Django 4.1.5 on 2023-02-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0046_alter_post_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publisher",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
