# Generated by Django 4.1.5 on 2023-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0048_remove_post_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
