# Generated by Django 4.1.5 on 2023-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0049_post_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reviewed",
            field=models.IntegerField(default=0),
        ),
    ]
