# Generated by Django 4.1.5 on 2023-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0050_post_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="new",
            field=models.CharField(default="None", max_length=30),
        ),
    ]
