# Generated by Django 4.1.5 on 2023-03-01 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0051_thread_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="last_message",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 1, 10, 37, 0, 339907)
            ),
        ),
    ]
