# Generated by Django 4.1.5 on 2023-03-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0052_thread_last_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="last_message",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
