# Generated by Django 4.1.5 on 2023-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0053_alter_thread_last_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="requested",
            field=models.CharField(default="none", max_length=30),
        ),
    ]
