# Generated by Django 4.1.5 on 2023-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0054_post_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="htmlfile",
            field=models.TextField(default=""),
        ),
    ]
