# Generated by Django 4.1.5 on 2023-03-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0055_post_htmlfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="htmlfile",
        ),
        migrations.AlterField(
            model_name="post",
            name="primary_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.tag"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="secondary_tags",
            field=models.ManyToManyField(
                blank=True, related_name="secondary_tag", to="blog.tag"
            ),
        ),
    ]
