# Generated by Django 4.1.5 on 2023-03-07 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0056_remove_post_htmlfile_alter_post_primary_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reviewers",
            field=models.ManyToManyField(
                related_name="reviewers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
