# Generated by Django 4.1.5 on 2023-03-07 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0057_post_reviewers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="reviewers",
        ),
    ]
