# Generated by Django 4.1.5 on 2023-03-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0060_post_requested_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="requested_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
