# Generated by Django 4.1.5 on 2023-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0062_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="new",
            field=models.IntegerField(default=0),
        ),
    ]
