# Generated by Django 4.1.5 on 2023-03-12 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0063_alter_notification_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 12, 10, 57, 23, 535329)
            ),
        ),
    ]
