# Generated by Django 4.1.5 on 2023-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0064_notification_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
