# Generated by Django 4.1.5 on 2023-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0065_alter_notification_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tags",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
