# Generated by Django 4.1.5 on 2023-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0066_alter_tag_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(upload_to="documents"),
        ),
    ]
