# Generated by Django 4.1.5 on 2023-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0067_alter_post_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="blob_data",
            field=models.TextField(blank=True, db_column="data"),
        ),
    ]
