# Generated by Django 4.1.5 on 2023-03-18 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0068_post_blob_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="blob_data",
            new_name="blob_file",
        ),
    ]
